In [3]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: sanju
Family Members: 4
Employee Salary: 80000
Employee Department: HR
Employee 2: 
Enter name: Srikanth
Family Members: 6
Employee Salary: 90000
Employee Department: Testing
Full Time Employee 1: 
Enter name: santu
Family Members: 5
Employee Salary: 100000
Employee Department: Management

Number of employees:  3
Avg salary is : 85000.0


In [4]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[ 4.55422848  2.14783648 19.52501111 14.5543913  11.693851   14.90245038
  9.28680996 18.16958702 10.5046681  18.92351859  4.85376213  3.04770424
 18.1038965   3.55752652  1.20570334  5.50205519  1.89463901 19.86182644
 13.09347191 16.7780543 ]




[[ 4.55422848  2.14783648 19.52501111 14.5543913  11.693851  ]
 [14.90245038  9.28680996 18.16958702 10.5046681  18.92351859]
 [ 4.85376213  3.04770424 18.1038965   3.55752652  1.20570334]
 [ 5.50205519  1.89463901 19.86182644 13.09347191 16.7780543 ]]


[[ 4.55422848  2.14783648  0.         14.5543913  11.693851  ]
 [14.90245038  9.28680996 18.16958702 10.5046681   0.        ]
 [ 4.85376213  3.04770424  0.          3.55752652  1.20570334]
 [ 5.50205519  1.89463901  0.         13.09347191 16.7780543 ]]
